-- ============================================================
-- SEVELIN POS — Stock ilimitado, reserva de stock en OT y
-- catálogo administrable de Áreas/Categorías de Repuestos
-- Archivo: sql/06-stock-ilimitado-areas-categorias.sql
-- Ejecutar en Supabase → SQL Editor, después de los scripts 01 a 05.
-- Es idempotente: puede correrse varias veces sin efectos secundarios.
-- ============================================================

-- 1. Stock ilimitado (servicios / ítems sin inventario físico real)
ALTER TABLE productos
  ADD COLUMN IF NOT EXISTS stock_ilimitado BOOLEAN DEFAULT FALSE;

ALTER TABLE repuestos
  ADD COLUMN IF NOT EXISTS stock_ilimitado BOOLEAN DEFAULT FALSE;

UPDATE productos SET stock_ilimitado = FALSE WHERE stock_ilimitado IS NULL;
UPDATE repuestos  SET stock_ilimitado = FALSE WHERE stock_ilimitado IS NULL;

-- 2. Trazabilidad: qué ítem de venta proviene de un repuesto ya reservado
--    en una Orden de Trabajo. Permite, al eliminar una venta, reabrir la
--    reserva en vez de devolver stock que en realidad sigue "usado".
ALTER TABLE venta_items
  ADD COLUMN IF NOT EXISTS ot_repuesto_id BIGINT NULL REFERENCES ot_repuestos(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_venta_items_ot_repuesto ON venta_items (ot_repuesto_id);

-- 3. Catálogo administrable de Áreas/Tipo y Categorías Base de Repuestos.
--    Antes estos valores solo existían como texto libre dentro de cada
--    repuesto; ahora quedan en su propia tabla para poder renombrarlos o
--    eliminarlos de forma centralizada (con "lápiz") sin tener que editar
--    repuesto por repuesto.
CREATE TABLE IF NOT EXISTS repuesto_areas (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre  TEXT NOT NULL UNIQUE,
  creado_en TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS repuesto_categorias (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre  TEXT NOT NULL UNIQUE,
  creado_en TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Se precargan valores sugeridos y se rescatan los que ya estén en uso
--    dentro de los repuestos existentes, para que la lista administrable
--    parta completa desde el primer momento.
INSERT INTO repuesto_areas (nombre) VALUES
  ('Teléfonos'), ('Laptops'), ('Consolas'), ('Componentes SMD'), ('Impresoras'), ('Tablets')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO repuesto_categorias (nombre) VALUES
  ('Batería'), ('Pantalla'), ('FPC'), ('Sub-Board'), ('BIOS'), ('Capacitores'),
  ('Conector de carga'), ('Teclado'), ('Bisagras'), ('Mano de obra')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO repuesto_areas (nombre)
  SELECT DISTINCT area FROM repuestos WHERE area IS NOT NULL AND area <> ''
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO repuesto_categorias (nombre)
  SELECT DISTINCT categoria FROM repuestos WHERE categoria IS NOT NULL AND categoria <> ''
ON CONFLICT (nombre) DO NOTHING;

-- 5. RLS: solo el backend (service_role) entra a estas dos tablas
ALTER TABLE repuesto_areas      ENABLE ROW LEVEL SECURITY;
ALTER TABLE repuesto_categorias ENABLE ROW LEVEL SECURITY;

-- 6. Comprobaciones rápidas (descomenta para revisar)
-- SELECT a.nombre, COUNT(r.id) AS repuestos_que_la_usan
--   FROM repuesto_areas a LEFT JOIN repuestos r ON r.area = a.nombre GROUP BY a.nombre ORDER BY 1;
-- SELECT c.nombre, COUNT(r.id) AS repuestos_que_la_usan
--   FROM repuesto_categorias c LEFT JOIN repuestos r ON r.categoria = c.nombre GROUP BY c.nombre ORDER BY 1;
