-- ============================================================
-- SEVELIN POS — Mermas, clasificaciones dinámicas de gastos
-- y corrección de fecha/hora en compras
-- Archivo: sql/08-mermas-clasificaciones.sql
-- Ejecutar en Supabase → SQL Editor, después de los scripts 01 a 07.
-- Es idempotente: puede correrse varias veces sin efectos secundarios.
-- ============================================================

-- ============================================================
-- 1. CLASIFICACIONES DINÁMICAS DE GASTOS
--    Antes eran una lista fija dentro de un CHECK en la tabla compras,
--    lo que impedía agregar categorías nuevas sin migrar la base.
-- ============================================================
CREATE TABLE IF NOT EXISTS compra_clasificaciones (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      TEXT NOT NULL UNIQUE,
  descripcion TEXT NULL,
  activo      BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en   TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- El CHECK fijo se elimina: ahora la validación la hace el backend contra
-- esta tabla. Sin esto, cualquier categoría nueva sería rechazada por
-- Postgres al insertar la compra.
ALTER TABLE compras DROP CONSTRAINT IF EXISTS compras_clasificacion_check;

INSERT INTO compra_clasificaciones (nombre, descripcion) VALUES
  ('Mercadería / Productos para Reventa',                  'Stock que se compra para vender en el POS'),
  ('Activo Fijo (Maquinaria, Herramientas, Equipamiento)', 'Bienes duraderos del negocio'),
  ('Insumos / Consumibles Taller',                         'Materiales que se consumen en las reparaciones'),
  ('Gastos Operativos (Servicios, Arriendo, Sueldos, etc.)', 'Gastos recurrentes de funcionamiento'),
  ('Impuestos / Contribuciones (SII, Tesorería, etc.)',    'Pagos tributarios y municipales'),
  ('Mermas / Pérdidas de Inventario',                      'Stock dado de baja por daño, robo o vencimiento')
ON CONFLICT (nombre) DO NOTHING;

-- Rescata cualquier clasificación que ya estuviera en uso en compras
-- históricas y que no esté en la lista anterior.
INSERT INTO compra_clasificaciones (nombre, descripcion)
  SELECT DISTINCT clasificacion, 'Recuperada de gastos ya registrados'
    FROM compras
   WHERE clasificacion IS NOT NULL AND clasificacion <> ''
ON CONFLICT (nombre) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_compra_clasif_activo ON compra_clasificaciones (activo);

-- ============================================================
-- 2. MERMAS / PÉRDIDAS DE INVENTARIO
--    Cada merma descuenta stock y genera automáticamente un gasto.
--    Se guarda el vínculo con ese gasto para poder auditarlo.
-- ============================================================
CREATE TABLE IF NOT EXISTS mermas (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo           TEXT NOT NULL,              -- 'PRODUCTO' | 'REPUESTO'
  producto_id    BIGINT NULL REFERENCES productos(id) ON DELETE SET NULL,
  repuesto_id    BIGINT NULL REFERENCES repuestos(id) ON DELETE SET NULL,
  nombre         TEXT NOT NULL,              -- se guarda el nombre por si el ítem se elimina después
  cantidad       NUMERIC NOT NULL,
  costo_unitario NUMERIC NOT NULL DEFAULT 0,
  costo_total    NUMERIC NOT NULL DEFAULT 0,
  observacion    TEXT NOT NULL,
  compra_id      BIGINT NULL REFERENCES compras(id) ON DELETE SET NULL,
  creado_en      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'mermas_tipo_check') THEN
    ALTER TABLE mermas ADD CONSTRAINT mermas_tipo_check CHECK (tipo IN ('PRODUCTO', 'REPUESTO'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_mermas_creado ON mermas (creado_en DESC);
CREATE INDEX IF NOT EXISTS idx_mermas_compra ON mermas (compra_id);

-- ============================================================
-- 3. ORIGEN DEL GASTO
--    Distingue un gasto cargado a mano de uno generado por una merma,
--    para poder filtrarlos y para no permitir editarlos a mano sin más.
-- ============================================================
ALTER TABLE compras
  ADD COLUMN IF NOT EXISTS origen TEXT DEFAULT 'MANUAL';

UPDATE compras SET origen = 'MANUAL' WHERE origen IS NULL;

CREATE INDEX IF NOT EXISTS idx_compras_origen ON compras (origen);

-- ============================================================
-- 4. Comprobaciones rápidas (descomenta para revisar)
-- ============================================================
-- SELECT nombre, activo FROM compra_clasificaciones ORDER BY id;
-- SELECT m.creado_en, m.nombre, m.cantidad, m.costo_total, c.clasificacion
--   FROM mermas m LEFT JOIN compras c ON c.id = m.compra_id ORDER BY m.id DESC LIMIT 10;
-- SELECT origen, COUNT(*), SUM(costo_total) FROM compras GROUP BY origen;
