-- ============================================================
-- SEVELIN POS — Lotes de costo (FIFO/PEPS) y comisión del POS Tuu
-- Archivo: sql/09-lotes-fifo-comision.sql
-- Ejecutar en Supabase → SQL Editor, después de los scripts 01 a 08.
-- Es idempotente: puede correrse varias veces sin efectos secundarios.
-- ============================================================
--
-- QUÉ AGREGA ESTE SCRIPT
--   1. productos.usa_lotes      → interruptor por producto, APAGADO por defecto.
--   2. producto_lotes           → capas de stock, cada una con su propio costo.
--   3. venta_item_lotes         → libro de consumo: qué capa pagó cada venta.
--   4. ventas.comision_pos      → comisión de la transacción con tarjeta.
--   5. fifo_consumir()          → descuenta por PEPS de forma atómica.
--   6. fifo_devolver()          → revierte el consumo al anular una venta.
--
-- NOTA SOBRE LA COMPATIBILIDAD
--   Ningún producto existente cambia de comportamiento: usa_lotes nace en
--   FALSE para todos, así que el POS sigue usando productos.costo_unitario
--   tal como hasta hoy. Los lotes solo se activan producto por producto y
--   a mano, desde el modal de producto.
-- ============================================================


-- ============================================================
-- 1. INTERRUPTOR POR PRODUCTO
--    DEFAULT FALSE + NOT NULL: los productos que ya existen y los que se
--    creen sin especificar nada quedan SIEMPRE en costo simple.
-- ============================================================
ALTER TABLE productos
  ADD COLUMN IF NOT EXISTS usa_lotes BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN productos.usa_lotes IS
  'TRUE = el costo sale de producto_lotes por PEPS. Se activa solo a mano.';


-- ============================================================
-- 2. CAPAS DE STOCK (LOTES)
--    cantidad          → unidades que quedan vivas en la capa
--    cantidad_inicial   → con cuántas entró (para auditoría e informes)
--    referencia         → texto libre: N° de factura, proveedor, guía, etc.
--    agotado_en         → se marca al llegar a 0. La capa NO se borra: si se
--                         borrara, una venta anulada no tendría a dónde
--                         devolver el stock y se perdería el historial de
--                         costos. Queda "cerrada" y fuera del FIFO.
-- ============================================================
CREATE TABLE IF NOT EXISTS producto_lotes (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id       BIGINT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
  cantidad          NUMERIC NOT NULL DEFAULT 0,
  cantidad_inicial  NUMERIC NOT NULL DEFAULT 0,
  costo_unitario    NUMERIC NOT NULL DEFAULT 0,
  referencia        TEXT NULL,
  creado_en         TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  agotado_en        TIMESTAMP WITH TIME ZONE NULL
);

-- El orden del FIFO es (creado_en, id): el id desempata dos lotes cargados
-- en el mismo segundo, cosa que pasa al importar varios de una vez.
CREATE INDEX IF NOT EXISTS idx_producto_lotes_fifo
  ON producto_lotes (producto_id, creado_en, id)
  WHERE agotado_en IS NULL;

CREATE INDEX IF NOT EXISTS idx_producto_lotes_producto
  ON producto_lotes (producto_id);


-- ============================================================
-- 3. LIBRO DE CONSUMO
--    Una línea de venta puede comerse varias capas ("5 del lote A y 3 del
--    lote B"), por eso el detalle no cabe en venta_items y vive aparte.
--    Sin esta tabla no se podría revertir una venta ni explicar de dónde
--    salió el costo que se le cobró.
-- ============================================================
CREATE TABLE IF NOT EXISTS venta_item_lotes (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id        BIGINT NULL REFERENCES ventas(id) ON DELETE CASCADE,
  venta_item_id   BIGINT NULL REFERENCES venta_items(id) ON DELETE CASCADE,
  producto_id     BIGINT NULL REFERENCES productos(id) ON DELETE SET NULL,
  lote_id         BIGINT NULL REFERENCES producto_lotes(id) ON DELETE SET NULL,
  cantidad        NUMERIC NOT NULL DEFAULT 0,
  costo_unitario  NUMERIC NOT NULL DEFAULT 0,
  creado_en       TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_venta_item_lotes_venta
  ON venta_item_lotes (venta_id);


-- ============================================================
-- 4. COMISIÓN DEL POS (TUU HAULMER PRO 2)
--    Se guarda el monto ya calculado en cada venta en vez de calcularlo al
--    vuelo en el reporte: si mañana Tuu cambia la fórmula, los informes
--    históricos siguen mostrando lo que realmente se pagó ese día.
-- ============================================================
ALTER TABLE ventas
  ADD COLUMN IF NOT EXISTS comision_pos NUMERIC NOT NULL DEFAULT 0;

COMMENT ON COLUMN ventas.comision_pos IS
  'Comisión cobrada por el POS Tuu en esta venta (0 si no fue con tarjeta).';


-- ============================================================
-- 5. CONSUMO FIFO ATÓMICO
--    Se resuelve en la base y no en Node por dos razones:
--      · FOR UPDATE bloquea las capas mientras se reparte la cantidad, así
--        dos cajas vendiendo a la vez no se llevan el mismo lote.
--      · Es una sola ida y vuelta en vez de N consultas por producto.
--
--    Devuelve una fila por capa consumida. Si el stock en lotes no alcanza,
--    consume todo lo que hay y devuelve el faltante en la última fila con
--    lote_id NULL, valorizado al costo_unitario del catálogo. Se prefiere
--    esto a lanzar un error: una caja nunca debe quedarse trabada por un
--    descuadre de inventario; el descuadre se corrige después.
-- ============================================================
CREATE OR REPLACE FUNCTION fifo_consumir(
  p_producto_id BIGINT,
  p_cantidad    NUMERIC
)
RETURNS TABLE (lote_id BIGINT, cantidad NUMERIC, costo_unitario NUMERIC)
LANGUAGE plpgsql
AS $$
DECLARE
  v_pendiente NUMERIC := COALESCE(p_cantidad, 0);
  v_toma      NUMERIC;
  v_lote      RECORD;
  v_costo_cat NUMERIC;
BEGIN
  IF v_pendiente <= 0 THEN RETURN; END IF;

  FOR v_lote IN
    SELECT l.id, l.cantidad AS disponible, l.costo_unitario AS costo
    FROM producto_lotes l
    WHERE l.producto_id = p_producto_id
      AND l.agotado_en IS NULL
      AND l.cantidad > 0
    ORDER BY l.creado_en ASC, l.id ASC
    FOR UPDATE
  LOOP
    EXIT WHEN v_pendiente <= 0;

    v_toma := LEAST(v_lote.disponible, v_pendiente);

    UPDATE producto_lotes
       SET cantidad   = cantidad - v_toma,
           -- Al llegar a 0 la capa se cierra y deja de entrar al FIFO
           agotado_en = CASE WHEN (cantidad - v_toma) <= 0 THEN NOW() ELSE NULL END
     WHERE id = v_lote.id;

    v_pendiente := v_pendiente - v_toma;

    lote_id        := v_lote.id;
    cantidad       := v_toma;
    costo_unitario := v_lote.costo;
    RETURN NEXT;
  END LOOP;

  -- Faltante: se vendió más de lo que había cargado en lotes.
  IF v_pendiente > 0 THEN
    SELECT COALESCE(p.costo_unitario, 0) INTO v_costo_cat
    FROM productos p WHERE p.id = p_producto_id;

    lote_id        := NULL;
    cantidad       := v_pendiente;
    costo_unitario := COALESCE(v_costo_cat, 0);
    RETURN NEXT;
  END IF;
END;
$$;


-- ============================================================
-- 6. DEVOLUCIÓN AL ANULAR UNA VENTA
--    Reabre la capa (agotado_en = NULL) y le repone las unidades. Como las
--    capas no se borran al agotarse, la devolución siempre encuentra dónde
--    dejar el stock y con qué costo.
-- ============================================================
CREATE OR REPLACE FUNCTION fifo_devolver(
  p_lote_id  BIGINT,
  p_cantidad NUMERIC
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
  IF p_lote_id IS NULL OR COALESCE(p_cantidad, 0) <= 0 THEN RETURN; END IF;

  UPDATE producto_lotes
     SET cantidad   = cantidad + p_cantidad,
         agotado_en = NULL
   WHERE id = p_lote_id;
END;
$$;


-- ============================================================
-- 7. VISTA DE APOYO — capas vigentes por producto
--    La usa la tabla de productos para mostrar "Lote 1: 5 un. a $2.000".
-- ============================================================
CREATE OR REPLACE VIEW v_producto_lotes_vigentes AS
SELECT
  l.producto_id,
  COUNT(*)                                   AS capas,
  SUM(l.cantidad)                            AS stock_en_lotes,
  SUM(l.cantidad * l.costo_unitario)         AS valor_en_lotes,
  CASE WHEN SUM(l.cantidad) > 0
       THEN SUM(l.cantidad * l.costo_unitario) / SUM(l.cantidad)
       ELSE 0 END                            AS costo_promedio
FROM producto_lotes l
WHERE l.agotado_en IS NULL AND l.cantidad > 0
GROUP BY l.producto_id;


-- ============================================================
-- 8. VERIFICACIÓN
--    Debe devolver 4 filas: usa_lotes, comision_pos y las dos tablas.
-- ============================================================
SELECT 'productos.usa_lotes'  AS objeto, COUNT(*)::TEXT AS existe
  FROM information_schema.columns
 WHERE table_name = 'productos' AND column_name = 'usa_lotes'
UNION ALL
SELECT 'ventas.comision_pos', COUNT(*)::TEXT
  FROM information_schema.columns
 WHERE table_name = 'ventas' AND column_name = 'comision_pos'
UNION ALL
SELECT 'tabla producto_lotes', COUNT(*)::TEXT
  FROM information_schema.tables WHERE table_name = 'producto_lotes'
UNION ALL
SELECT 'tabla venta_item_lotes', COUNT(*)::TEXT
  FROM information_schema.tables WHERE table_name = 'venta_item_lotes';
