-- ============================================================
-- SEVELIN POS — Pago mixto (varios medios en una misma venta)
-- Archivo: sql/10-pago-mixto.sql
-- Ejecutar en Supabase → SQL Editor, después del 09.
-- Idempotente: puede correrse varias veces.
-- ============================================================
--
-- POR QUÉ UNA TABLA Y NO UNA COLUMNA
--   Un cliente puede pagar $20.000 con $12.000 en efectivo y $8.000 con
--   débito. Guardar eso como texto en ventas.metodo_pago haría imposible
--   dos cosas importantes:
--
--     1. Calcular bien la COMISIÓN del POS Tuu. La comisión se cobra solo
--        sobre lo que pasa por la máquina, así que hay que saber el monto
--        exacto de la parte con tarjeta. Con "Efectivo + Débito" en un
--        campo de texto no se puede.
--     2. Cuadrar la caja por medio de pago al cierre del día.
--
--   Con `venta_pagos` cada parte queda con su monto y todo se puede sumar.
--
-- COMPATIBILIDAD
--   Las ventas de un solo medio SIGUEN funcionando igual: guardan su
--   método en ventas.metodo_pago y no generan filas en venta_pagos. Nada
--   de lo existente cambia de comportamiento.
-- ============================================================


-- ============================================================
-- 1. DESGLOSE DE PAGOS
-- ============================================================
CREATE TABLE IF NOT EXISTS venta_pagos (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id   BIGINT NOT NULL REFERENCES ventas(id) ON DELETE CASCADE,
  metodo     TEXT NOT NULL,
  monto      NUMERIC NOT NULL DEFAULT 0,
  -- Comisión que le corresponde a ESTA parte (0 si no fue con tarjeta)
  comision   NUMERIC NOT NULL DEFAULT 0,
  creado_en  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_venta_pagos_venta ON venta_pagos (venta_id);
CREATE INDEX IF NOT EXISTS idx_venta_pagos_metodo ON venta_pagos (metodo);

COMMENT ON TABLE venta_pagos IS
  'Desglose de una venta pagada con varios medios. Vacío si fue un solo medio.';


-- ============================================================
-- 2. BANDERA EN LA CABECERA
--    Evita tener que consultar venta_pagos para saber si hay desglose.
-- ============================================================
ALTER TABLE ventas
  ADD COLUMN IF NOT EXISTS pago_mixto BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN ventas.pago_mixto IS
  'TRUE = la venta se pagó con varios medios; el detalle está en venta_pagos.';


-- ============================================================
-- 3. VISTA DE CUADRATURA POR MEDIO DE PAGO
--    Unifica las ventas de un solo medio con las mixtas, para poder
--    cuadrar la caja sin tratar dos casos distintos.
-- ============================================================
CREATE OR REPLACE VIEW v_ventas_por_medio AS
-- Ventas de un solo medio
SELECT
  v.id           AS venta_id,
  v.fecha,
  COALESCE(v.metodo_pago_final, v.metodo_pago) AS metodo,
  v.total        AS monto,
  v.comision_pos AS comision
FROM ventas v
WHERE v.estado = 'PAGADA' AND NOT v.pago_mixto

UNION ALL

-- Ventas mixtas: una fila por cada parte
SELECT
  p.venta_id,
  v.fecha,
  p.metodo,
  p.monto,
  p.comision
FROM venta_pagos p
JOIN ventas v ON v.id = p.venta_id
WHERE v.estado = 'PAGADA';


-- ============================================================
-- 4. VERIFICACIÓN
--    Debe devolver 2 filas con existe = 1.
-- ============================================================
SELECT 'tabla venta_pagos' AS objeto, COUNT(*)::TEXT AS existe
  FROM information_schema.tables WHERE table_name = 'venta_pagos'
UNION ALL
SELECT 'ventas.pago_mixto', COUNT(*)::TEXT
  FROM information_schema.columns
 WHERE table_name = 'ventas' AND column_name = 'pago_mixto';
