-- ============================================================
-- SEVELIN POS — Módulo de Finanzas y Balance
-- Archivo: sql/11-finanzas-balance.sql
-- Ejecutar en Supabase → SQL Editor, después del 10.
-- Idempotente: puede correrse varias veces.
-- ============================================================
--
-- QUÉ AGREGA
--   1. compra_clasificaciones.grupo  → agrupa los gastos en las 3
--      familias del balance (operativo / inventario / inversión).
--   2. gastos_fijos                  → arriendo, internet, sueldos…
--   3. inyecciones_capital           → aportes de dinero propio a la caja.
--   4. v_balance_ventas              → vista de apoyo para el dashboard.
--
-- POR QUÉ LAS INYECCIONES VAN APARTE Y NO COMO "VENTA"
--   Meter un aporte de capital como venta inflaría los ingresos y la
--   utilidad, que es justo lo que se quiere medir. Pero el dinero SÍ
--   entra al cajón, así que tiene que aparecer en el arqueo. Por eso
--   tabla propia: suma a la caja y no toca el estado de resultados.
-- ============================================================


-- ============================================================
-- 1. GRUPO CONTABLE DE CADA CLASIFICACIÓN DE GASTO
-- ============================================================
ALTER TABLE compra_clasificaciones
  ADD COLUMN IF NOT EXISTS grupo TEXT NOT NULL DEFAULT 'OPERATIVO';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.constraint_column_usage
    WHERE table_name = 'compra_clasificaciones' AND constraint_name = 'compra_clasificaciones_grupo_check'
  ) THEN
    ALTER TABLE compra_clasificaciones
      ADD CONSTRAINT compra_clasificaciones_grupo_check
      CHECK (grupo IN ('OPERATIVO', 'INVENTARIO', 'INVERSION'));
  END IF;
END $$;

COMMENT ON COLUMN compra_clasificaciones.grupo IS
  'OPERATIVO = arriendo, servicios, sueldos · INVENTARIO = mercadería para revender · INVERSION = activos y capital';

/* Clasificación inicial por nombre. Solo toca las que siguen en el valor
   por defecto, así una corrección manual nunca se pisa al reejecutar. */
UPDATE compra_clasificaciones SET grupo = 'INVENTARIO'
 WHERE grupo = 'OPERATIVO'
   AND (nombre ILIKE '%mercader%' OR nombre ILIKE '%stock%' OR nombre ILIKE '%product%'
     OR nombre ILIKE '%insumo%'   OR nombre ILIKE '%repuesto%' OR nombre ILIKE '%merma%');

UPDATE compra_clasificaciones SET grupo = 'INVERSION'
 WHERE grupo = 'OPERATIVO'
   AND (nombre ILIKE '%activo%' OR nombre ILIKE '%herramienta%' OR nombre ILIKE '%equipo%'
     OR nombre ILIKE '%maquin%'  OR nombre ILIKE '%inversi%'   OR nombre ILIKE '%mobiliario%');


-- ============================================================
-- 2. GASTOS FIJOS / RECURRENTES
--    No generan filas en `compras` por sí solos: son una PLANTILLA de
--    lo que se espera pagar cada mes. Sirven para el punto de equilibrio
--    y para no olvidar registrarlos.
--    `dia_mes` es el día en que corresponde pagarlo (1-31).
-- ============================================================
CREATE TABLE IF NOT EXISTS gastos_fijos (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre         TEXT NOT NULL,
  monto          NUMERIC NOT NULL DEFAULT 0,
  dia_mes        INTEGER NOT NULL DEFAULT 1 CHECK (dia_mes BETWEEN 1 AND 31),
  clasificacion  TEXT,
  grupo          TEXT NOT NULL DEFAULT 'OPERATIVO'
                 CHECK (grupo IN ('OPERATIVO', 'INVENTARIO', 'INVERSION')),
  -- Pausar en vez de borrar: un gasto de temporada vuelve el año siguiente
  activo         BOOLEAN NOT NULL DEFAULT TRUE,
  notas          TEXT,
  creado_en      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  actualizado_en TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_gastos_fijos_activo ON gastos_fijos (activo);

COMMENT ON TABLE gastos_fijos IS
  'Plantilla de gastos recurrentes. No son movimientos: alimentan el punto de equilibrio.';


-- ============================================================
-- 3. INYECCIONES DE CAPITAL
--    Aportes de dinero propio al negocio. Entran a la caja pero NO son
--    ingresos por ventas.
-- ============================================================
CREATE TABLE IF NOT EXISTS inyecciones_capital (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha       DATE NOT NULL DEFAULT CURRENT_DATE,
  monto       NUMERIC NOT NULL DEFAULT 0,
  metodo      TEXT NOT NULL DEFAULT 'Efectivo',
  descripcion TEXT,
  creado_en   TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_inyecciones_fecha ON inyecciones_capital (fecha);

COMMENT ON TABLE inyecciones_capital IS
  'Aportes de capital propio. Suman a la caja, NO a los ingresos por ventas.';


-- ============================================================
-- 4. VISTA DE APOYO PARA EL BALANCE
--    Normaliza el medio de pago de cada venta cobrada, resolviendo el
--    caso mixto: una venta con desglose aporta una fila por parte.
--    Sin esto habría que tratar dos casos distintos en cada consulta.
-- ============================================================
CREATE OR REPLACE VIEW v_balance_ventas AS
-- Ventas de un solo medio
SELECT
  v.id                                          AS venta_id,
  v.fecha,
  COALESCE(v.metodo_pago_final, v.metodo_pago)  AS metodo,
  v.total                                       AS monto,
  v.costo_total,
  v.utilidad,
  v.comision_pos
FROM ventas v
WHERE v.estado = 'PAGADA' AND NOT COALESCE(v.pago_mixto, FALSE)

UNION ALL

/* Ventas mixtas: una fila por parte. El costo y la utilidad se dejan en
   0 salvo en la primera parte, para no contarlos varias veces al sumar
   por medio de pago. */
SELECT
  p.venta_id,
  v.fecha,
  p.metodo,
  p.monto,
  0, 0,
  p.comision
FROM venta_pagos p
JOIN ventas v ON v.id = p.venta_id
WHERE v.estado = 'PAGADA';


-- ============================================================
-- 5. VERIFICACIÓN — debe devolver 3 filas con existe = 1
-- ============================================================
SELECT 'tabla gastos_fijos' AS objeto, COUNT(*)::TEXT AS existe
  FROM information_schema.tables WHERE table_name = 'gastos_fijos'
UNION ALL
SELECT 'tabla inyecciones_capital', COUNT(*)::TEXT
  FROM information_schema.tables WHERE table_name = 'inyecciones_capital'
UNION ALL
SELECT 'compra_clasificaciones.grupo', COUNT(*)::TEXT
  FROM information_schema.columns
 WHERE table_name = 'compra_clasificaciones' AND column_name = 'grupo';
