-- ============================================================
-- SEVELIN POS — Medio de pago en gastos + Arqueo de caja
-- Archivo: sql/12-arqueo-medios-gasto.sql
-- Ejecutar después del 11. Idempotente.
-- ============================================================
--
-- QUÉ RESUELVE
--   1. compras.metodo_pago → hasta ahora la caja física del balance
--      asumía que TODOS los gastos salían en efectivo, porque no había
--      dónde guardar cómo se pagó cada uno. Si el arriendo se paga por
--      transferencia, esa plata nunca salió del cajón y la cifra
--      quedaba baja.
--
--   2. arqueos → la caja física partía de 0 cada período. Faltaba el
--      fondo con que se abre el cajón y el conteo real al cerrar, que
--      es lo que permite detectar diferencias.
-- ============================================================


-- ============================================================
-- 1. MEDIO DE PAGO DE CADA GASTO
--    Por defecto 'Efectivo': es el criterio conservador y coincide con
--    lo que el balance asumía antes, así que los gastos ya registrados
--    no cambian de comportamiento al migrar.
-- ============================================================
ALTER TABLE compras
  ADD COLUMN IF NOT EXISTS metodo_pago TEXT NOT NULL DEFAULT 'Efectivo';

CREATE INDEX IF NOT EXISTS idx_compras_metodo ON compras (metodo_pago);

COMMENT ON COLUMN compras.metodo_pago IS
  'Con qué se pagó el gasto. Solo los pagados en Efectivo descuentan de la caja física.';

/* Las mermas no son una salida de dinero: son stock que se perdió. El
   gasto existe para la contabilidad, pero del cajón no salió un peso,
   así que se marcan aparte para no descontarlas de la caja física. */
UPDATE compras SET metodo_pago = 'No aplica (merma)'
 WHERE origen = 'MERMA' AND metodo_pago = 'Efectivo';


-- ============================================================
-- 2. ARQUEOS DE CAJA
--    Un arqueo por día (o por turno). Guarda con cuánto se abrió, cuánto
--    se contó al cerrar y la diferencia contra lo esperado.
--
--    `esperado` se guarda congelado en vez de recalcularse después: si
--    mañana se corrige una venta antigua, el arqueo de ayer debe seguir
--    mostrando lo que se vio ese día. Un arqueo es una foto, no un
--    cálculo vivo.
-- ============================================================
CREATE TABLE IF NOT EXISTS arqueos (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha          DATE NOT NULL DEFAULT CURRENT_DATE,
  fondo_inicial  NUMERIC NOT NULL DEFAULT 0,
  -- Se llenan al cerrar; NULL mientras la caja sigue abierta
  contado        NUMERIC NULL,
  esperado       NUMERIC NULL,
  diferencia     NUMERIC NULL,
  observaciones  TEXT,
  cerrado        BOOLEAN NOT NULL DEFAULT FALSE,
  abierto_en     TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  cerrado_en     TIMESTAMP WITH TIME ZONE NULL
);

/* Un solo arqueo por fecha: evita dos aperturas el mismo día, que
   dejaría dos fondos iniciales compitiendo. */
CREATE UNIQUE INDEX IF NOT EXISTS idx_arqueos_fecha ON arqueos (fecha);

COMMENT ON TABLE arqueos IS
  'Apertura y cierre de caja. El fondo inicial es la base de la caja física del día.';


-- ============================================================
-- 3. VERIFICACIÓN — debe devolver 2 filas con existe = 1
-- ============================================================
SELECT 'compras.metodo_pago' AS objeto, COUNT(*)::TEXT AS existe
  FROM information_schema.columns
 WHERE table_name = 'compras' AND column_name = 'metodo_pago'
UNION ALL
SELECT 'tabla arqueos', COUNT(*)::TEXT
  FROM information_schema.tables WHERE table_name = 'arqueos';
