-- ============================================================
-- SEVELIN POS — Utilidades, IVA crédito fiscal y remanente
-- Archivo: sql/27-utilidades-iva-credito.sql · Ejecutar después del 26.
-- Idempotente: se puede correr varias veces sin romper nada.
-- ------------------------------------------------------------
-- PARA QUÉ
--   El submódulo "Utilidades" necesita separar el IVA que el negocio
--   DEBE enterar al SII del dinero que de verdad es utilidad. Hasta
--   ahora `compras` no guardaba nada de IVA, así que solo se podía
--   calcular el IVA débito (el de las ventas con DTE) y se sobreestimaba
--   lo que hay que pagar: faltaba el crédito fiscal de las compras con
--   factura.
--
--   1. compras.tiene_factura  → si ese gasto da derecho a crédito fiscal.
--   2. compras.iva_credito    → cuánto IVA trae esa factura (en pesos).
--   3. iva_ajustes            → correcciones manuales del remanente de
--                               crédito fiscal, con justificación. Sirve
--                               sobre todo para cargar el remanente que
--                               venía de ANTES de usar el sistema.
--
-- POR QUÉ EL IVA CRÉDITO SE GUARDA EN PESOS Y NO SE CALCULA
--   No todo gasto con factura trae 19% exacto: hay boletas exentas,
--   compras a proveedores sin IVA, notas de crédito y montos que ya
--   vienen netos. Guardar la cifra real de la factura es más fiel que
--   derivarla, y permite corregirla sin tocar el monto del gasto.
-- ============================================================

-- 1. Crédito fiscal por gasto -------------------------------------------
ALTER TABLE compras
  ADD COLUMN IF NOT EXISTS tiene_factura BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS iva_credito   NUMERIC NOT NULL DEFAULT 0;

COMMENT ON COLUMN compras.tiene_factura IS
  'TRUE si el gasto está respaldado con factura y da derecho a crédito fiscal IVA.';
COMMENT ON COLUMN compras.iva_credito IS
  'IVA en pesos de la factura del gasto (crédito fiscal). 0 si no tiene factura.';

-- Un gasto sin factura nunca debe arrastrar crédito fiscal
UPDATE compras SET iva_credito = 0 WHERE tiene_factura = FALSE AND iva_credito <> 0;

-- El crédito fiscal nunca puede superar al monto total del gasto
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'compras_iva_credito_check') THEN
    ALTER TABLE compras ADD CONSTRAINT compras_iva_credito_check
      CHECK (iva_credito >= 0 AND iva_credito <= costo_total);
  END IF;
END $$;

-- Filtrar "las compras con factura del período" es la consulta caliente
CREATE INDEX IF NOT EXISTS idx_compras_tiene_factura
  ON compras (tiene_factura) WHERE tiene_factura = TRUE;

-- 2. Ajustes manuales del remanente de crédito fiscal --------------------
-- Mismo criterio que `ajustes_saldo` (sql/16): se guarda un DELTA con
-- justificación obligatoria, nunca un saldo absoluto. El remanente real
-- se recalcula sumando el histórico + estos ajustes, así que no hay un
-- número guardado que pueda quedar desincronizado.
CREATE TABLE IF NOT EXISTS public.iva_ajustes (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha      DATE NOT NULL DEFAULT CURRENT_DATE,
  monto      NUMERIC NOT NULL,          -- positivo suma remanente, negativo lo baja
  motivo     TEXT NOT NULL,
  usuario    TEXT NULL,
  creado_en  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

COMMENT ON TABLE public.iva_ajustes IS
  'Correcciones manuales al remanente de crédito fiscal IVA. Delta con justificación, nunca saldo absoluto.';

CREATE INDEX IF NOT EXISTS idx_iva_ajustes_fecha ON public.iva_ajustes (fecha);

-- El backend entra con service_role (omite RLS), igual que el resto del
-- POS. Se activa RLS igual para que la tabla no quede abierta si algún
-- día se expone una llave anon.
ALTER TABLE public.iva_ajustes ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- VERIFICACIÓN (opcional, correr a mano)
--   SELECT column_name FROM information_schema.columns
--    WHERE table_name = 'compras' AND column_name IN ('tiene_factura','iva_credito');
--   SELECT COUNT(*) FROM public.iva_ajustes;
-- ------------------------------------------------------------
