-- 48 · Registro de errores para el panel Salud
-- ============================================
-- EL PROBLEMA (dueño, 12-09-2026)
-- Los errores reales (una base que no responde, un correo que no salió, una
-- integración caída) solo quedaban en los logs de Vercel, que se borran en
-- una hora y que el dueño no revisa. Se enteraba por un aviso rojo suelto
-- en pantalla, sin saber si era algo de una vez o algo que se repetía.
--
-- LA REGLA
-- Todo error de servidor (respuesta 5xx) y toda falla de integración queda
-- en esta tabla, y Página Web → Salud los muestra agrupados: qué falló,
-- dónde, cuántas veces y cuándo fue la última. La tienda tiene su propia
-- tabla gemela en su base (sevelin-tienda/supabase/33): si una de las dos
-- bases se cae, la otra igual registra.
--
-- Nunca se guardan llaves ni tokens (se enmascaran antes de insertar).
-- Se conserva 30 días.
--
-- Idempotente.

create table if not exists registro_errores (
  id          bigint generated by default as identity primary key,
  creado_en   timestamptz not null default now(),
  origen      text not null,              -- 'POS'
  ruta        text null,                  -- '/api/pos/pedidos-web'
  metodo      text null,                  -- 'GET'
  estado_http integer null,               -- 500
  mensaje     text not null,              -- lo que falló, ya sin secretos
  detalle     text null
);

create index if not exists idx_registro_errores_creado on registro_errores (creado_en desc);

-- Solo el backend (service_role) entra.
alter table registro_errores enable row level security;

comment on table registro_errores is
  'Errores de servidor e integraciones del POS, para el panel Salud. Sin secretos. Se conserva 30 días.';
