-- 51 · RCV del SII automático + semáforo de IVA del mes
-- ======================================================
-- EL PROBLEMA (dueño, 13-09-2026)
-- Pagó más de $760.000 de IVA en un mes por vender con boleta sin tener
-- crédito suficiente, y no tenía cómo ver EN EL MES cuánto crédito le queda.
-- El IVA de las compras vive en el Registro de Compras y Ventas (RCV) del
-- SII, no en el POS (nadie lo carga a mano).
--
-- LA SOLUCIÓN
-- Un robot del POS (cron diario de Vercel) entra al SII con el certificado
-- digital del dueño —cargado por él en las variables de Vercel, nunca en el
-- repo ni en la base— y guarda aquí:
--   · sii_rcv_resumen     → totales por tipo de documento (lo que muestra la
--                           portada del RCV). De acá sale el débito y el crédito.
--   · sii_rcv_documentos  → cada factura recibida (y emitida), con su IVA.
--                           Mismo formato que el CSV que se descarga a mano,
--                           así que el respaldo "subir CSV" usa la misma tabla.
--   · sii_sync            → historial de cada intento (para Salud y para decir
--                           "actualizado hace 3 horas").
-- Y `iva_remanentes` guarda el código 77 del F29, que
-- es el crédito que pasa al mes siguiente (el SII no lo entrega en el RCV).
--
-- Solo lectura del SII: el robot nunca acepta, reclama ni declara nada.
--
-- Idempotente.

create table if not exists sii_rcv_resumen (
  periodo        text not null check (periodo ~ '^[0-9]{6}$'),           -- 'AAAAMM'
  operacion      text not null check (operacion in ('COMPRA', 'VENTA')),
  estado         text not null,                                          -- REGISTRO, PENDIENTE, RECLAMADO, NO_INCLUIR
  tipo_doc       integer not null,                                       -- 33 factura, 39 boleta, 61 nota de crédito…
  nombre_doc     text null,
  total_docs     integer not null default 0,
  exento         numeric not null default 0,
  neto           numeric not null default 0,
  iva            numeric not null default 0,
  iva_no_recuperable numeric not null default 0,
  total          numeric not null default 0,
  actualizado_en timestamptz not null default now(),
  primary key (periodo, operacion, estado, tipo_doc)
);

create table if not exists sii_rcv_documentos (
  id             bigint generated by default as identity primary key,
  periodo        text not null check (periodo ~ '^[0-9]{6}$'),
  operacion      text not null check (operacion in ('COMPRA', 'VENTA')),
  estado         text not null default 'REGISTRO',
  tipo_doc       integer not null,
  rut            text not null,                -- del proveedor (compra) o del cliente (venta)
  razon_social   text null,
  folio          bigint not null,
  fecha_doc      date null,
  exento         numeric not null default 0,
  neto           numeric not null default 0,
  iva            numeric not null default 0,
  iva_no_recuperable numeric not null default 0,
  total          numeric not null default 0,
  fuente         text not null default 'robot' check (fuente in ('robot', 'csv')),
  actualizado_en timestamptz not null default now(),
  unique (operacion, tipo_doc, rut, folio)
);
create index if not exists sii_rcv_documentos_periodo_idx on sii_rcv_documentos (periodo, operacion, estado);

create table if not exists sii_sync (
  id          bigint generated by default as identity primary key,
  creado_en   timestamptz not null default now(),
  origen      text not null check (origen in ('robot', 'manual', 'csv')),
  ok          boolean not null,
  periodos    text null,
  documentos  integer not null default 0,
  mensaje     text null
);
create index if not exists sii_sync_creado_idx on sii_sync (creado_en desc);

alter table sii_rcv_resumen    enable row level security;
alter table sii_rcv_documentos enable row level security;
alter table sii_sync           enable row level security;

-- Remanente de crédito fiscal (código 77 del F29) que pasa al mes siguiente.
-- Tabla propia y no una columna de f29_presentaciones: se conoce desde la
-- PROPUESTA del SII, antes de presentar, y el semáforo lo necesita igual.
-- (Una primera versión de esta migración lo puso como columna; se quita.)
alter table f29_presentaciones drop column if exists remanente_siguiente;

create table if not exists iva_remanentes (
  periodo        text primary key check (periodo ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),  -- mes declarado 'AAAA-MM'
  monto          numeric not null check (monto >= 0),
  fuente         text null,                                                    -- 'propuesta F29', 'F29 presentado'
  actualizado_en timestamptz not null default now()
);
alter table iva_remanentes enable row level security;

comment on table iva_remanentes is
  'Código 77 del F29 por período: crédito que pasa al mes siguiente. Lo usa el semáforo de IVA (sql/51).';

-- Agosto 2026, de la propuesta del SII que entregó el dueño el 13-09-2026.
insert into iva_remanentes (periodo, monto, fuente)
values ('2026-08', 219227, 'propuesta F29')
on conflict (periodo) do nothing;
