-- 56 · Cada compra de mercadería: cuándo llegó y hasta cuándo se devuelve
-- =======================================================================
-- EL PROBLEMA (dueño, 16-09-2026)
-- "Compré 50 ventiladores: ¿se están vendiendo al ritmo que esperaba o me
--  conviene devolverlos y comprarlos en otra fecha?" · "Compré 20 monitores
--  para navidad y al 1 de enero me sobran 10."
-- Hoy el POS no sabe NADA de eso: `productos.stock` es un número sin
-- historia. No hay fecha de compra, no hay cuántas entraron juntas, y sobre
-- todo no hay hasta cuándo el proveedor las recibe de vuelta — que es el
-- único dato que convierte "me sobran 10" en una decisión con plazo.
--
-- POR QUÉ UNA TABLA NUEVA Y NO `producto_lotes` (sql/09)
-- `producto_lotes` existe para el COSTO por PEPS y solo funciona con
-- `productos.usa_lotes` encendido (hoy: 1 producto de 185). Encenderlo
-- cambia de dónde sale el costo de cada venta — o sea, cambia la utilidad
-- de ese producto. Anotar una fecha de compra no puede tener ese efecto
-- secundario. Por eso esto vive aparte y NO toca el costeo de nada.
--
-- QUÉ SÍ HACE: guarda la entrada tal como ocurrió (fecha, cantidad, costo,
-- proveedor y plazo de devolución). El análisis de rotación se calcula
-- encima, en el servidor, y nunca se guarda: un número guardado envejece
-- mal y después se lee como si fuera de hoy.
--
-- `devolucion_hasta` es NULL cuando el proveedor no recibe devoluciones.
-- Es distinto de una fecha ya pasada: NULL = "nunca hubo ventana",
-- pasada = "la ventana se cerró". El informe los trata distinto.
--
-- Idempotente.

create table if not exists ingresos_mercaderia (
  id                bigint generated by default as identity primary key,
  producto_id       bigint not null references productos(id) on delete cascade,
  fecha_compra      date not null,
  cantidad          numeric not null check (cantidad > 0),
  costo_unitario    numeric not null default 0 check (costo_unitario >= 0),
  proveedor         text null,
  -- Hasta cuándo el proveedor recibe de vuelta lo que no se vendió.
  -- NULL = no acepta devoluciones (distinto de una fecha ya vencida).
  devolucion_hasta  date null,
  referencia        text null,        -- N° de factura, guía, orden de compra
  nota              text null,
  -- Vínculo opcional con el gasto ya registrado en `compras`, para no
  -- tener que anotar el mismo desembolso dos veces.
  compra_id         bigint null references compras(id) on delete set null,
  creado_en         timestamptz not null default now(),
  creado_por        text null,
  -- Se cierra a mano cuando la entrada ya no interesa (se devolvió, se
  -- liquidó, se dio por agotada). No se borra: el historial de compras es
  -- justamente lo que hace útil esta tabla.
  cerrado_en        timestamptz null,
  cerrado_motivo    text null check (cerrado_motivo is null or cerrado_motivo in ('devuelto', 'vendido', 'liquidado', 'otro'))
);

create index if not exists ingresos_mercaderia_producto_idx
  on ingresos_mercaderia (producto_id, fecha_compra);

-- Los dos informes preguntan por lo MISMO: entradas abiertas con plazo de
-- devolución que todavía corre.
create index if not exists ingresos_mercaderia_devolucion_idx
  on ingresos_mercaderia (devolucion_hasta) where cerrado_en is null and devolucion_hasta is not null;

-- RLS: el frontend nunca habla con Supabase directo (solo el backend con
-- service_role, que la omite). Sin esto la tabla quedaría abierta a la
-- llave anónima — el olvido que ya costó dos alertas críticas en la tienda.
alter table ingresos_mercaderia enable row level security;

comment on table ingresos_mercaderia is
  'Cada compra de mercadería que entró: fecha, cantidad, costo y hasta cuándo el proveedor la recibe de vuelta. NO participa del costeo (eso es producto_lotes, sql/09): sirve para medir rotación y decidir devoluciones a tiempo (sql/56).';
comment on column ingresos_mercaderia.devolucion_hasta is
  'Último día para devolverle al proveedor lo que no se vendió. NULL = no acepta devoluciones, distinto de una fecha ya pasada (la ventana se cerró).';
comment on column ingresos_mercaderia.cerrado_en is
  'Entrada dada por terminada a mano (devuelta, vendida, liquidada). No se borra nunca: el historial es lo que hace útil la tabla.';
