-- 69 · Sellos de garantía Sevelin con número de serie, por OT (v97, 28-09-2026)
-- ===========================================================================
-- EL PEDIDO (dueño, 28-09-2026)
-- "Mis sellos de garantía traen número de serie. En reparaciones y
--  mantenciones quiero registrar el S/N del sello (uno o varios) que le pongo
--  al equipo: en la OT, en el comprobante de entrega, y que se pueda buscar
--  por ese S/N en Garantías."
--
-- POR QUÉ UNA TABLA Y NO UNA COLUMNA text[] EN ordenes_trabajo
-- Un sello físico va en UN solo equipo. Con una tabla, el S/N es único en la
-- base: no se puede registrar el mismo sello en dos órdenes (error de tipeo o
-- sello reutilizado), y buscar un sello devuelve una sola orden, sin dudas.
-- Antes de esto no existía nada parecido: el único S/N de una OT era
-- dispositivo_sn (el del equipo del cliente), que es otra cosa.
--
-- El S/N se guarda normalizado por el servidor: sin espacios y en mayúsculas.
-- Idempotente. Tabla nueva → RLS activo sin políticas (solo la service_role).

create table if not exists ot_sellos_garantia (
  id bigint generated by default as identity primary key,
  ot_id bigint not null references ordenes_trabajo(id) on delete cascade,
  numero_serie text not null,
  creado_en timestamptz not null default now(),
  constraint ot_sellos_garantia_numero_serie_formato
    check (numero_serie ~ '^[A-Z0-9][A-Z0-9._/-]{0,39}$')
);

create unique index if not exists ot_sellos_garantia_numero_serie_unico
  on ot_sellos_garantia (numero_serie);
create index if not exists ot_sellos_garantia_ot_id
  on ot_sellos_garantia (ot_id);

alter table ot_sellos_garantia enable row level security;

comment on table ot_sellos_garantia is
  'Sellos de garantía Sevelin (con S/N) puestos en el equipo de una OT. Un S/N solo puede estar en una orden.';
comment on column ot_sellos_garantia.numero_serie is
  'S/N impreso en el sello, normalizado (sin espacios, mayúsculas).';
