-- 84 · Correcciones de stock con clave del dueño (v118, 04-10-2026)
-- ======================================================================
-- EL PEDIDO (dueño, 03-10-2026)
-- "Que cada stock se cargue a través de fecha de compra, unidades, costo y
-- precio de venta, y que si yo por X razón quiero cambiar el STOCK ACTUAL
-- se necesite el permiso de admin, y se pregunte: si estoy restando, si
-- quiero asumir la merma o dar por perdido o no hacer nada; y si sumo, si
-- agregar el gasto de este producto o no hacer nada."
--
-- LA REGLA
--   · El stock ya no se escribe en la ficha del producto: sube con una
--     compra (ingresos_mercaderia, sql/56) y se corrige solo con
--     POST /api/productos/:id/ajuste-stock, que pide la clave del dueño.
--   · Cada corrección dice por qué:
--       danado   se dañó            → merma (pérdida al costo en Finanzas)
--       perdido  se perdió o robaron → merma (pérdida al costo en Finanzas)
--       conteo   estaba mal contado  → solo corrige el número
--       compra   lo compró           → queda como compra (sql/56)
--   · Esta tabla es el REGISTRO de cada corrección: cuánto había, cuánto
--     quedó, por qué y quién. Sin ella un "estaba mal contado" no dejaría
--     rastro en ninguna parte.
--
-- No mueve plata por sí sola: la pérdida la anota la merma (tabla mermas +
-- gasto "Mermas / Pérdidas de Inventario") y la compra queda en
-- ingresos_mercaderia. Acá solo se guarda el vínculo.
-- RLS activo y sin políticas: solo el backend (service_role). Idempotente.

create table if not exists ajustes_stock (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references productos(id) on delete cascade,
  stock_antes numeric not null,
  stock_despues numeric not null check (stock_despues >= 0),
  motivo text not null check (motivo in ('danado', 'perdido', 'conteo', 'compra')),
  nota text null check (nota is null or length(nota) <= 300),
  -- Con cuánto se valorizó la merma o la compra. NULL en un "mal contado".
  costo_unitario numeric null,
  costo_total numeric null,
  merma_id bigint null references mermas(id) on delete set null,
  ingreso_id bigint null references ingresos_mercaderia(id) on delete set null,
  creado_por text not null default 'admin',
  creado_en timestamptz not null default now(),
  check (stock_despues <> stock_antes)
);

create index if not exists ajustes_stock_producto on ajustes_stock (producto_id, creado_en desc);

alter table ajustes_stock enable row level security;

comment on table ajustes_stock is
  'Registro de cada corrección manual de stock (v118): cuánto había, cuánto quedó, por qué y quién. Pide la clave del dueño. Sin políticas: solo service_role.';
